name:                reactb
version:             0.1.0
github:              "eunikolsky/reactb"
license:             BSD3
author:              "Eugene Nikolsky"
maintainer:          "e@egeek.me"
copyright:           "2023 Eugene Nikolsky"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eunikolsky/reactb#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -fhide-source-paths
- -Wnoncanonical-monad-instances
- -Werror=incomplete-record-updates
- -Werror=incomplete-patterns
- -Werror=incomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wmissing-deriving-strategies
- -Wunused-packages
- -Werror=missing-fields
- -Werror=missing-methods
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=empty-enumerations
- -Werror=missing-home-modules

default-extensions:
- BangPatterns
- BinaryLiterals
- DeriveGeneric
- DerivingStrategies
- FlexibleInstances
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- TypeApplications

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - http-types
    - random-strings
    - servant-options
    - servant-server
    - wai
    - wai-cors
    - wai-extra
    - warp

executables:
  reactb:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - reactb

tests:
  reactb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - aeson-qq
    - base
    - hspec
    - reactb
